baseURL = "https://www.robvanmierlo.dev/"
languageCode = "en-us"
title = "Blog of Rob van Mierlo"
theme = "casper"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"

[params]
  description = "I <3 making web site"
  mainIcon = "/img/hugo.png"

[[params.social]]
    title = "Twitter"
    url = "https://twitter.com/Rupke75"
[[params.social]]
    title = "Github"
    url = "https://github.com/rvanmierlo"
[[params.social]]
    title = "Linkedin"
    url = "https://www.linkedin.com/in/rob-van-mierlo-b968585/"
